import _ from 'underscore'

export default {

	state: [
		{currency: 'Abkhazian apsar', symbol: '', code: ''},
		{currency: 'Russian ruble', symbol: '', code: 'RUB'},
		{currency: 'Afghan afghani', symbol: '؋', code: 'AFN'},
		{currency: 'Euro', symbol: '€', code: 'EUR'},
		{currency: 'Albanian lek', symbol: 'L', code: 'ALL'},
		{currency: 'Alderney pound', symbol: '£', code: ''},
		{currency: 'British pound', symbol: '£', code: 'GBP'},
		{currency: 'Guernsey pound', symbol: '£', code: 'GGP'},
		{currency: 'Algerian dinar', symbol: 'د.ج', code: 'DZD'},
		{currency: 'Angolan kwanza', symbol: 'Kz', code: 'AOA'},
		{currency: 'East Caribbean dollar', symbol: '$', code: 'XCD'},
		{currency: 'Argentine peso', symbol: '$', code: 'ARS'},
		{currency: 'Armenian dram', symbol: '', code: 'AMD'},
		{currency: 'Aruban florin', symbol: 'ƒ', code: 'AWG'},
		{currency: 'Australian dollar', symbol: '$', code: 'AUD'},
		{currency: 'Azerbaijani manat', symbol: '', code: 'AZN'},
		{currency: 'Bahamian dollar', symbol: '$', code: 'BSD'},
		{currency: 'Bahraini dinar', symbol: '.د.ب', code: 'BHD'},
		{currency: 'Bangladeshi taka', symbol: '৳', code: 'BDT'},
		{currency: 'Barbadian dollar', symbol: '$', code: 'BBD'},
		{currency: 'Belarusian ruble', symbol: 'Br', code: 'BYR'},
		{currency: 'Belize dollar', symbol: '$', code: 'BZD'},
		{currency: 'West African CFA franc', symbol: 'Fr', code: 'XOF'},
		{currency: 'Bermudian dollar', symbol: '$', code: 'BMD'},
		{currency: 'Bhutanese ngultrum', symbol: 'Nu', code: 'BTN'},
		{currency: 'Indian rupee', symbol: '₹', code: 'INR'},
		{currency: 'Bolivian boliviano', symbol: 'Bs.', code: 'BOB'},
		{currency: 'United States dollar', symbol: '$.', code: 'USD'},
		{currency: 'Bosnia and Herzegovina convertible mark', symbol: 'KM', code: 'BAM'},
		{currency: 'Botswana pula', symbol: 'P', code: 'BWP'},
		{currency: 'Brazilian real', symbol: 'R$', code: 'BRL'},
		{currency: 'Brunei dollar', symbol: '$', code: 'BND'},
		{currency: 'Singapore dollar', symbol: '$', code: 'SGD'},
		{currency: 'Bulgarian lev', symbol: 'лв', code: 'BGN'},
		{currency: 'Burundian franc', symbol: 'Fr', code: 'BIF'},
		{currency: 'Cambodian riel', symbol: '៛', code: 'KHR'},
		{currency: 'Canadian dollar', symbol: '$', code: 'CAD'},
		{currency: 'Cape Verdean escudo', symbol: 'Esc', code: 'CVE'},
		{currency: 'Cayman Islands dollar', symbol: '$', code: 'KYD'},
		{currency: 'Chilean peso', symbol: '$', code: 'CLP'},
		{currency: 'Chinese yuan', symbol: '¥', code: 'CNY'},
		{currency: 'Colombian peso', symbol: '$', code: 'COP'},
		{currency: 'Comorian franc', symbol: 'Fr', code: 'KMF'},
		{currency: 'Congolese franc', symbol: 'Fr', code: 'CDF'},
		{currency: 'Central African CFA franc', symbol: 'Fr', code: 'XAF'},
		{currency: 'New Zealand dollar', symbol: '$', code: 'NZD'},
		{currency: 'Cook Islands dollar', symbol: '$', code: ''},
		{currency: 'Costa Rican colón', symbol: '₡', code: 'CRC'},
		{currency: 'Croatian kuna', symbol: 'kn', code: 'HRK'},
		{currency: 'Cuban peso', symbol: '$', code: 'CUP'},
		{currency: 'Netherlands Antillean guilder', symbol: 'ƒ', code: 'ANG'},
		{currency: 'Czech koruna', symbol: 'Kč', code: 'CZK'},
		{currency: 'Danish krone', symbol: 'kr', code: 'DKK'},
		{currency: 'Djiboutian franc', symbol: 'Fr', code: 'DJF'},
		{currency: 'Dominican peso', symbol: '$', code: 'DOP'},
		{currency: 'Egyptian pound', symbol: '£', code: 'EGP'},
		{currency: 'Eritrean nakfa', symbol: 'Nfk', code: 'ERN'},
		{currency: 'Ethiopian birr', symbol: 'Br', code: 'ETB'},
		{currency: 'Falkland Islands pound', symbol: '£', code: 'FKP'},
		{currency: 'Faroese króna', symbol: 'kr', code: ''},
		{currency: 'Fijian dollar', symbol: '$', code: 'FJD'},
		{currency: 'CFP franc', symbol: 'Fr', code: 'XPF'},
		{currency: 'Gambian dalasi', symbol: 'D', code: 'GMD'},
		{currency: 'Georgian lari', symbol: 'ლ', code: 'GEL'},
		{currency: 'Ghana cedi', symbol: '₵', code: 'GHS'},
		{currency: 'Gibraltar pound', symbol: '£', code: 'GIP'},
		{currency: 'Guatemalan quetzal', symbol: 'Q', code: 'GTQ'},
		{currency: 'Guinean franc', symbol: 'Fr', code: 'GNF'},
		{currency: 'Guyanese dollar', symbol: '$', code: 'GYD'},
		{currency: 'Haitian gourde', symbol: 'G', code: 'HTG'},
		{currency: 'Honduran lempira', symbol: 'L', code: 'HNL'},
		{currency: 'Hong Kong dollar', symbol: '$', code: 'HKD'},
		{currency: 'Hungarian forint', symbol: 'Ft', code: 'HUF'},
		{currency: 'Icelandic króna', symbol: 'kr', code: 'ISK'},
		{currency: 'Indian rupee', symbol: '₹', code: 'INR'},
		{currency: 'Indonesian rupiah', symbol: 'Rp', code: 'IDR'},
		{currency: 'Iranian rial', symbol: '', code: 'IRR'},
		{currency: 'Iraqi dinar', symbol: 'ع.د', code: 'IQD'},
		{currency: 'Manx pound', symbol: '£', code: 'IMP'},
		{currency: 'Israeli new shekel', symbol: '₪', code: 'ILS'},
		{currency: 'Jamaican dollar', symbol: '$', code: 'JMD'},
		{currency: 'Japanese yen', symbol: '¥', code: 'JPY'},
		{currency: 'Jersey pound', symbol: '£', code: 'JEP'},
		{currency: 'Jordanian dinar', symbol: 'د.ا', code: 'JOD'},
		{currency: 'Kazakhstani tenge', symbol: '', code: 'KZT'},
		{currency: 'Kenyan shilling', symbol: 'Sh', code: 'KES'},
		{currency: 'Kiribati dollar', symbol: '$', code: ''},
		{currency: 'North Korean won', symbol: '₩', code: 'KPW'},
		{currency: 'South Korean won', symbol: '₩', code: 'KRW'},
		{currency: 'Kuwaiti dinar', symbol: 'د.ك', code: 'KWD'},
		{currency: 'Kyrgyzstani som', symbol: 'лв', code: 'KGS'},
		{currency: 'Lao kip', symbol: '₭', code: '₭'},
		{currency: 'Lebanese pound', symbol: 'ل.ل', code: 'LBP'},
		{currency: 'Lesotho loti', symbol: 'L', code: 'LSL'},
		{currency: 'South African rand', symbol: 'R', code: 'ZAR'},
		{currency: 'Liberian dollar', symbol: '$', code: 'LRD'},
		{currency: 'Libyan dinar', symbol: 'ل.د', code: 'LYD'},
		{currency: 'Swiss franc', symbol: 'Fr', code: 'CHF'},
		{currency: 'Macanese pataca', symbol: 'P', code: 'MOP'},
		{currency: 'Macedonian denar', symbol: 'ден', code: 'MKD'},
		{currency: 'Malagasy ariary', symbol: 'Ar', code: 'MGA'},
		{currency: 'Malawian kwacha', symbol: 'MK', code: 'MWK'},
		{currency: 'Malaysian ringgit', symbol: 'RM', code: 'MYR'},
		{currency: 'Maldivian rufiyaa', symbol: '.ރ', code: 'MVR'},
		{currency: 'Mauritanian ouguiya', symbol: 'UM', code: 'MRO'},
		{currency: 'Mauritian rupee', symbol: '₨', code: 'MUR'},
		{currency: 'Mexican peso', symbol: '$', code: 'MXN'},
		{currency: 'Moldovan leu', symbol: 'L', code: 'MDL'},
		{currency: 'Mongolian tögrög', symbol: '₮', code: 'MNT'},
		{currency: 'Moroccan dirham', symbol: 'د.م.', code: 'MAD'},
		{currency: 'Mozambican metical', symbol: 'MT', code: 'MZN'},
		{currency: 'Burmese kyat', symbol: 'Ks', code: 'MMK'},
		{currency: 'Armenian dram', symbol: '', code: 'AMD'},
		{currency: 'Namibian dollar', symbol: '$', code: 'NAD'},
		{currency: 'Nepalese rupee', symbol: '₨', code: 'NPR'},
		{currency: 'Nicaraguan córdoba', symbol: 'C$', code: 'NIO'},
		{currency: 'Nigerian naira', symbol: '₦', code: 'NGN'},
		{currency: 'Turkish lira', symbol: '', code: 'TRY'},
		{currency: 'Norwegian krone', symbol: 'kr', code: 'NOK'},
		{currency: 'Omani rial', symbol: 'ر.ع.', code: 'OMR'},
		{currency: 'Pakistani rupee', symbol: '₨.', code: 'PKR'},
		{currency: 'Papua New Guinean kina', symbol: 'K', code: 'PGK'},
		{currency: 'Paraguayan guaraní', symbol: '₲', code: 'PYG'},
		{currency: 'Peruvian nuevo sol', symbol: 'S/.', code: 'PEN'},
		{currency: 'Philippine peso', symbol: '₱', code: 'PHP'},
		{currency: 'Polish złoty', symbol: 'zł', code: 'PLN'},
		{currency: 'Qatari riyal', symbol: 'ر.ق', code: 'QAR'},
		{currency: 'Romanian leu', symbol: 'lei', code: 'RON'},
		{currency: 'Russian ruble', symbol: '', code: 'RUB'},
		{currency: 'Rwandan franc', symbol: 'Fr', code: 'RWF'},
		{currency: 'Samoan tālā', symbol: 'T', code: 'WST'},
		{currency: 'São Tomé and Príncipe dobra', symbol: 'Db', code: 'STD'},
		{currency: 'Saudi riyal', symbol: 'ر.س', code: 'SAR'},
		{currency: 'Serbian dinar', symbol: 'дин', code: 'RSD'},
		{currency: 'Seychellois rupee', symbol: '₨', code: 'SCR'},
		{currency: 'Sierra Leonean leone', symbol: 'Le', code: 'SLL'},
		{currency: 'Solomon Islands dollar', symbol: '$', code: 'SBD'},
		{currency: 'Somali shilling', symbol: 'Sh', code: 'SOS'},
		{currency: 'Somaliland shilling', symbol: 'Sh', code: ''},
		{currency: 'South African rand', symbol: 'R', code: 'ZAR'},
		{currency: 'South Sudanese pound', symbol: '£', code: 'SSP'},
		{currency: 'Sri Lankan rupee', symbol: 'Rs', code: 'LKR'},
		{currency: 'Sudanese pound', symbol: 'ج.س.', code: 'SDG'},
		{currency: 'Surinamese dollar', symbol: '$', code: 'SRD'},
		{currency: 'Swazi lilangeni', symbol: 'L', code: 'SZL'},
		{currency: 'Swedish krona', symbol: 'kr', code: 'SEK'},
		{currency: 'Swiss franc', symbol: 'Fr', code: 'CHF'},
		{currency: 'Syrian pound', symbol: '£', code: 'SYP'},
		{currency: 'New Taiwan dollar', symbol: '$', code: 'TWD'},
		{currency: 'Tajikistani somoni', symbol: 'ЅМ', code: 'TJS'},
		{currency: 'Tanzanian shilling', symbol: 'Sh', code: 'TZS'},
		{currency: 'Thai baht', symbol: '฿', code: 'THB'},
		{currency: 'Tongan paʻanga', symbol: 'T$', code: 'TOP'},
		{currency: 'Transnistrian ruble', symbol: 'р.', code: 'PRB'},
		{currency: 'Trinidad and Tobago dollar', symbol: '$', code: 'TTD'},
		{currency: 'Saint Helena pound', symbol: '£', code: 'SHP'},
		{currency: 'Tunisian dinar', symbol: 'د.ت', code: 'TND'},
		{currency: 'Turkmenistan manat', symbol: 'm', code: 'TMT'},
		{currency: 'Tuvaluan dollar', symbol: '$', code: ''},
		{currency: 'Ugandan shilling', symbol: 'Sh', code: 'UGX'},
		{currency: 'United Arab Emirates dirham', symbol: 'د.إ', code: 'AED'},
		{currency: 'Uruguayan peso', symbol: '$', code: 'UYU'},
		{currency: 'Uzbekistani som', symbol: '', code: 'UZS'},
		{currency: 'Vanuatu vatu', symbol: 'Vt', code: 'VUV'},
		{currency: 'Venezuelan bolívar', symbol: 'Bs F', code: 'VEF'},
		{currency: 'Vietnamese đồng', symbol: '₫', code: 'VND'},
		{currency: 'Yemeni rial', symbol: '', code: 'YER'},
		{currency: 'Zambian kwacha', symbol: 'ZK', code: 'ZMW'},
	],

	getCurrencies() {
		return this.state;
	},

	getCurrencyByCode(code) {

	}

}